In [ ]:
! pip install crowd-kit

In [ ]:
import pandas as pd
from crowdkit.aggregation import GoldMajorityVote

In [ ]:
golden_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/results with golden.csv", delimiter=";")

In [ ]:
golden_df

    INPUT:id              ASSIGNMENT:worker_id  GOLDEN:presence
0       2_16  d464c878d6045495bf456c109561fa0f             True
1       2_16  ed884ac8d75ed7e67dd2c59d789cbc69             True
2       2_16  fd010cde0617e7b65482c9e34c47dd1a             True
3      22_39  d464c878d6045495bf456c109561fa0f             True
4      22_39  ed884ac8d75ed7e67dd2c59d789cbc69             True
..       ...                               ...              ...
129      2_8  fd010cde0617e7b65482c9e34c47dd1a            False
130      2_9  e94e098631657a40b13f9f99ccb81ca9            False
131      2_9  ed884ac8d75ed7e67dd2c59d789cbc69            False
132      2_9  d464c878d6045495bf456c109561fa0f            False
133      2_9  fd010cde0617e7b65482c9e34c47dd1a            False

[134 rows x 3 columns]

In [ ]:
results_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/results only presence.csv", delimiter=";")

In [ ]:
results_df

    INPUT:id              ASSIGNMENT:worker_id  OUTPUT:presence
0       1_10  d464c878d6045495bf456c109561fa0f             True
1       1_10  ed884ac8d75ed7e67dd2c59d789cbc69             True
2       1_11  d464c878d6045495bf456c109561fa0f            False
3       1_11  ed884ac8d75ed7e67dd2c59d789cbc69            False
4       1_11  6ee90e7b60ff3b982edf4af8b028a0c2            False
..       ...                               ...              ...
665    67_13  e94e098631657a40b13f9f99ccb81ca9            False
666     67_2  fd010cde0617e7b65482c9e34c47dd1a            False
667     67_3  fd010cde0617e7b65482c9e34c47dd1a            False
668     67_5  fd010cde0617e7b65482c9e34c47dd1a             True
669      8_1  ed884ac8d75ed7e67dd2c59d789cbc69            False

[670 rows x 3 columns]

In [ ]:
def subsample(x):
    if len(x) > 2:
        return pd.DataFrame(x).sample(3)

In [ ]:
input_dict = results_df.groupby("INPUT:id").apply(len).to_dict()

In [ ]:
df = results_df.groupby("INPUT:id").apply(subsample)

In [ ]:
rows = []
for i in df.iterrows():
    if input_dict[i[1]["INPUT:id"]] > 2:
        rows.append(i[1])

In [ ]:
rows

[INPUT:id                                            1_11
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_11, 2), dtype: object,
 INPUT:id                                            1_11
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_11, 3), dtype: object,
 INPUT:id                                            1_11
 ASSIGNMENT:worker_id    6ee90e7b60ff3b982edf4af8b028a0c2
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_11, 4), dtype: object,
 INPUT:id                                            1_12
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (1_12, 7), dtype: object,
 INPUT:id                                            1_12
 ASSIGNMENT:worker_id    e94e098631657a40b13f9f99ccb81ca9
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (1_12, 5), dtype: object,
 INPUT:id                                            1_12
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (1_12, 6), dtype: object,
 INPUT:id                                            1_13
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_13, 8), dtype: object,
 INPUT:id                                            1_13
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_13, 9), dtype: object,
 INPUT:id                                            1_13
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_13, 10), dtype: object,
 INPUT:id                                            1_14
 ASSIGNMENT:worker_id    6ee90e7b60ff3b982edf4af8b028a0c2
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_14, 14), dtype: object,
 INPUT:id                                            1_14
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_14, 13), dtype: object,
 INPUT:id                                            1_14
 ASSIGNMENT:worker_id    e94e098631657a40b13f9f99ccb81ca9
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_14, 12), dtype: object,
 INPUT:id                                            1_15
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (1_15, 15), dtype: object,
 INPUT:id                                            1_15
 ASSIGNMENT:worker_id    6ee90e7b60ff3b982edf4af8b028a0c2
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (1_15, 17), dtype: object,
 INPUT:id                                            1_15
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (1_15, 18), dtype: object,
 INPUT:id                                            1_16
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_16, 20), dtype: object,
 INPUT:id                                            1_16
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_16, 22), dtype: object,
 INPUT:id                                            1_16
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_16, 21), dtype: object,
 INPUT:id                                            1_17
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (1_17, 23), dtype: object,
 INPUT:id                                            1_17
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (1_17, 25), dtype: object,
 INPUT:id                                            1_17
 ASSIGNMENT:worker_id    6ee90e7b60ff3b982edf4af8b028a0c2
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_17, 24), dtype: object,
 INPUT:id                                            1_19
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_19, 27), dtype: object,
 INPUT:id                                            1_19
 ASSIGNMENT:worker_id    e94e098631657a40b13f9f99ccb81ca9
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_19, 28), dtype: object,
 INPUT:id                                            1_19
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_19, 26), dtype: object,
 INPUT:id                                            1_20
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_20, 29), dtype: object,
 INPUT:id                                            1_20
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_20, 31), dtype: object,
 INPUT:id                                            1_20
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_20, 30), dtype: object,
 INPUT:id                                            1_21
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_21, 33), dtype: object,
 INPUT:id                                            1_21
 ASSIGNMENT:worker_id    e94e098631657a40b13f9f99ccb81ca9
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_21, 32), dtype: object,
 INPUT:id                                            1_21
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_21, 35), dtype: object,
 INPUT:id                                            1_23
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_23, 39), dtype: object,
 INPUT:id                                            1_23
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_23, 38), dtype: object,
 INPUT:id                                            1_23
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_23, 40), dtype: object,
 INPUT:id                                            1_24
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (1_24, 42), dtype: object,
 INPUT:id                                            1_24
 ASSIGNMENT:worker_id    6ee90e7b60ff3b982edf4af8b028a0c2
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_24, 43), dtype: object,
 INPUT:id                                            1_24
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_24, 45), dtype: object,
 INPUT:id                                            1_25
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_25, 47), dtype: object,
 INPUT:id                                            1_25
 ASSIGNMENT:worker_id    e94e098631657a40b13f9f99ccb81ca9
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_25, 46), dtype: object,
 INPUT:id                                            1_25
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_25, 49), dtype: object,
 INPUT:id                                            1_27
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_27, 54), dtype: object,
 INPUT:id                                            1_27
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_27, 52), dtype: object,
 INPUT:id                                            1_27
 ASSIGNMENT:worker_id    e94e098631657a40b13f9f99ccb81ca9
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_27, 53), dtype: object,
 INPUT:id                                             1_8
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_8, 55), dtype: object,
 INPUT:id                                             1_8
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_8, 57), dtype: object,
 INPUT:id                                             1_8
 ASSIGNMENT:worker_id    e94e098631657a40b13f9f99ccb81ca9
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (1_8, 56), dtype: object,
 INPUT:id                                             2_1
 ASSIGNMENT:worker_id    6ee90e7b60ff3b982edf4af8b028a0c2
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_1, 63), dtype: object,
 INPUT:id                                             2_1
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_1, 64), dtype: object,
 INPUT:id                                             2_1
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_1, 61), dtype: object,
 INPUT:id                                            2_11
 ASSIGNMENT:worker_id    e94e098631657a40b13f9f99ccb81ca9
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_11, 67), dtype: object,
 INPUT:id                                            2_11
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_11, 69), dtype: object,
 INPUT:id                                            2_11
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_11, 68), dtype: object,
 INPUT:id                                            2_14
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (2_14, 73), dtype: object,
 INPUT:id                                            2_14
 ASSIGNMENT:worker_id    e94e098631657a40b13f9f99ccb81ca9
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_14, 72), dtype: object,
 INPUT:id                                            2_14
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (2_14, 75), dtype: object,
 INPUT:id                                            2_15
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_15, 78), dtype: object,
 INPUT:id                                            2_15
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_15, 77), dtype: object,
 INPUT:id                                            2_15
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_15, 76), dtype: object,
 INPUT:id                                            2_16
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (2_16, 80), dtype: object,
 INPUT:id                                            2_16
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_16, 81), dtype: object,
 INPUT:id                                            2_16
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (2_16, 79), dtype: object,
 INPUT:id                                            2_17
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_17, 83), dtype: object,
 INPUT:id                                            2_17
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_17, 85), dtype: object,
 INPUT:id                                            2_17
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_17, 82), dtype: object,
 INPUT:id                                            2_18
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_18, 88), dtype: object,
 INPUT:id                                            2_18
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_18, 86), dtype: object,
 INPUT:id                                            2_18
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_18, 87), dtype: object,
 INPUT:id                                            2_19
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (2_19, 92), dtype: object,
 INPUT:id                                            2_19
 ASSIGNMENT:worker_id    ed884ac8d75ed7e67dd2c59d789cbc69
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_19, 91), dtype: object,
 INPUT:id                                            2_19
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_19, 89), dtype: object,
 INPUT:id                                             2_2
 ASSIGNMENT:worker_id    e94e098631657a40b13f9f99ccb81ca9
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (2_2, 95), dtype: object,
 INPUT:id                                             2_2
 ASSIGNMENT:worker_id    6ee90e7b60ff3b982edf4af8b028a0c2
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_2, 96), dtype: object,
 INPUT:id                                             2_2
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (2_2, 94), dtype: object,
 INPUT:id                                            2_21
 ASSIGNMENT:worker_id    e94e098631657a40b13f9f99ccb81ca9
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_21, 99), dtype: object,
 INPUT:id                                            2_21
 ASSIGNMENT:worker_id    d464c878d6045495bf456c109561fa0f
 OUTPUT:presence                                    False
 length                                               NaN
 Name: (2_21, 101), dtype: object,
 INPUT:id                                            2_21
 ASSIGNMENT:worker_id    fd010cde0617e7b65482c9e34c47dd1a
 OUTPUT:presence                                     True
 length                                               NaN
 Name: (2_21, 102), dtype: object,
 INPUT:id                                            2_22

In [ ]:
df = pd.DataFrame(rows)

In [ ]:
def count_string(x):
    input = x["INPUT:id"][0]
    answers = x["OUTPUT:presence"].to_numpy()
    counts = np.unique(answers, return_counts=True)
    ind = np.argmax(counts[1])
    return input, counts[0][ind], counts[1][ind]

In [ ]:
counts = df.groupby("INPUT:id").apply(count_string).to_list()

In [ ]:
final_df = pd.DataFrame(counts, columns=["INPUT:id", "answer", "support"])

In [ ]:
final_df

    INPUT:id  answer  support
0       1_11   False        3
1       1_12    True        3
2       1_13   False        3
3       1_14   False        3
4       1_15    True        3
..       ...     ...      ...
179     64_9   False        3
180     65_1    True        2
181     66_1   False        3
182    67_11   False        3
183    67_13   False        2

[184 rows x 3 columns]

In [ ]:
final_df.to_csv('results_processed.csv')

In [ ]:
res_dict = {}
for i, raw in df.iterrows():
    if df["INPUT:id"][i] == df["INPUT:id"][i+1] == df["INPUT:id"][i+2]:

          INPUT:id              ASSIGNMENT:worker_id  OUTPUT:presence  length
1_11  2       1_11  d464c878d6045495bf456c109561fa0f            False     NaN
      3       1_11  ed884ac8d75ed7e67dd2c59d789cbc69            False     NaN
      4       1_11  6ee90e7b60ff3b982edf4af8b028a0c2            False     NaN
1_12  7       1_12  d464c878d6045495bf456c109561fa0f             True     NaN
      5       1_12  e94e098631657a40b13f9f99ccb81ca9             True     NaN
...            ...                               ...              ...     ...
67_11 661    67_11  ed884ac8d75ed7e67dd2c59d789cbc69            False     NaN
      662    67_11  d464c878d6045495bf456c109561fa0f            False     NaN
67_13 664    67_13  ed884ac8d75ed7e67dd2c59d789cbc69            False     NaN
      665    67_13  e94e098631657a40b13f9f99ccb81ca9            False     NaN
      663    67_13  d464c878d6045495bf456c109561fa0f             True     NaN

[552 rows x 4 columns]

In [ ]:
results_df.groupby("INPUT:id")

In [ ]:
import numpy as np

In [ ]:
np.unique(results_df["ASSIGNMENT:worker_id"].to_numpy(), return_counts=True)

(array(['6ee90e7b60ff3b982edf4af8b028a0c2',
        'd464c878d6045495bf456c109561fa0f',
        'e94e098631657a40b13f9f99ccb81ca9',
        'ed884ac8d75ed7e67dd2c59d789cbc69',
        'fd010cde0617e7b65482c9e34c47dd1a'], dtype=object),
 array([ 50, 180, 110, 190, 140]))